/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/accounts — list the caller's accounts, oldest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of accounts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** POST /api/accounts — create an account owned by the caller, encrypting both credentials. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewAccount"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Name conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/accounts/:id — fetch one of the caller's accounts (no credentials). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * PUT /api/accounts/:id — update name/venue/type; credentials are re-encrypted only if
         * @description supplied (otherwise the stored ciphertext is kept via COALESCE).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccount"];
                };
            };
            responses: {
                /** @description Updated account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** DELETE /api/accounts/:id — delete one of the caller's accounts. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Account ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/auth/me — validate the Bearer token and return the caller's profile. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/runs — list the caller's runs, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of runs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * POST /api/runs — launch a run binding a strategy to an account and an ordered set of
         * @description symbols. Validates ownership, that every symbol is tradable on the account's venue, and
         *     that the strategy compiles, then snapshots a [`RunManifest`] and records it as `running`.
         *     No engine process is spawned — this is control-plane bookkeeping for now.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LaunchRequest"];
                };
            };
            responses: {
                /** @description Run launched */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Strategy, account or symbol not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/runs/:id — fetch one of the caller's runs. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** DELETE /api/runs/:id — delete a run record. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/equity-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/runs/:id/equity-curve — downsampled cumulative realized-PnL curve. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Downsampled equity curve points */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EquityPoint"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/runs/:id/live — latest cached live snapshot (raw JSON published by the engine).
         * @description `404` when Redis isn't configured or nothing has been published yet for this run.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest live snapshot JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found or Redis not configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/runs/:id/live/stream — Server-Sent Events stream of live snapshots: the current
         * @description cached snapshot first, then one event per published update. `404` when Redis isn't configured.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of live run snapshots (text/event-stream) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/runs/:id/stop — transition a running run to `stopped`. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stopped run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run is not in a stoppable state */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/runs/:id/summary — headline performance metrics, computed from parquet on read. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Headline performance metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunSummary"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/symbol-pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/runs/:id/symbol-pnl — per-symbol PnL attribution. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Per-symbol PnL attribution */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SymbolPnlSummary"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/runs/:id/trades?page=&size= — paginated trade history (newest first). */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (0-indexed, default 0) */
                    page?: number | null;
                    /** @description Page size (default 100) */
                    size?: number | null;
                };
                header?: never;
                path: {
                    /** @description Run ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated trade history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradePage"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/strategies — list the caller's strategies, oldest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of strategies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** POST /api/strategies — create a strategy owned by the caller (no validation gate). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StrategyInput"];
                };
            };
            responses: {
                /** @description Strategy created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/feature-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/strategies/feature-catalog — the fields + functions available to feature
         * @description DSL expressions, sorted by name. Static (derived from the engine registries).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available fields and functions for feature DSL expressions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/strategies/validate — compile Rhai source and report parse errors (no DB write). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ValidateRequest"];
                };
            };
            responses: {
                /** @description Validation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/validate-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/strategies/validate-features — compile each feature DSL expression and report the
         * @description ones that fail, positioned by index and name (no DB write).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ValidateFeaturesRequest"];
                };
            };
            responses: {
                /** @description Feature validation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/strategies/:id — fetch one of the caller's strategies. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Strategy ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Strategy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** PUT /api/strategies/:id — update name/description/type/code. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Strategy ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StrategyInput"];
                };
            };
            responses: {
                /** @description Updated strategy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Strategy"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** DELETE /api/strategies/:id — delete one of the caller's strategies. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Strategy ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/symbols?venue_id=<uuid> — list symbols (optionally filtered to a venue). */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by venue ID */
                    venue_id?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of symbols */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Symbol"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/venues — list all venues, oldest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of venues */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Venue"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** POST /api/venues — create a venue. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewVenue"];
                };
            };
            responses: {
                /** @description Venue created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Venue"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Name conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/venues/:id — fetch a single venue. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Venue ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Venue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Venue"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** PUT /api/venues/:id — update name and venue_type. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Venue ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateVenue"];
                };
            };
            responses: {
                /** @description Updated venue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Venue"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** DELETE /api/venues/:id — delete a venue. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Venue ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Still referenced by accounts */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{id}/symbols/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/venues/:id/symbols/sync — fetch the venue's exchange instrument list and upsert. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Venue ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Symbols synced and delisted count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Venue not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An account as returned to API clients. Credentials are intentionally **omitted** — they
         *     are write-only and never leave the server in plaintext or ciphertext.
         */
        Account: {
            account_type: components["schemas"]["AccountType"];
            /** Format: date-time */
            created_at: string;
            fee: components["schemas"]["FeeConfig"];
            /** Format: uuid */
            id: string;
            name: string;
            risk: components["schemas"]["RiskConfig"];
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            venue_id: string;
        };
        /**
         * @description The kind of account / margin mode at a venue. Snake_case is the canonical
         *     wire/storage form, shared by the JSON API and the Postgres `accounts.account_type`
         *     text column.
         * @enum {string}
         */
        AccountType: "spot" | "cross_margin" | "isolated_margin" | "linear_futures" | "inverse_futures";
        /**
         * @description One downsampled point on the equity curve. `equity`/`pnl` are cumulative realized PnL (the
         *     run is assumed to start flat at 0); `ts` is epoch milliseconds of the closing fill.
         */
        EquityPoint: {
            /** Format: double */
            equity: number;
            /** Format: double */
            pnl: number;
            /** Format: int64 */
            ts: number;
        };
        /**
         * @description Per-run execution settings. Some fields are **universal** (apply to every mode); others are
         *     **simulation-only** (paper/backtest) and are ignored by the live gateway — the UI hides the
         *     latter in live mode, and they fall back to harmless defaults.
         */
        ExecutionSettings: {
            /**
             * Format: double
             * @description Fraction of simulated resting orders randomly cancelled.
             */
            cancel_ratio?: number;
            /**
             * Format: double
             * @description How far price may move (in ticks) before a resting order chases it.
             */
            chase_threshold_ticks?: number;
            latency?: components["schemas"]["LatencyModel"];
            /**
             * Format: double
             * @description Max child-order size when slicing a parent order.
             */
            max_slice_size?: number;
            /** Format: double */
            stop_loss_points?: number;
            /** Format: double */
            take_profit_points?: number;
            /**
             * Format: int64
             * @description TWAP slice interval.
             */
            twap_interval_ms?: number;
        };
        /**
         * @description One feature the strategy consumes: a `name` and an alpha-engine DSL `expression`
         *     (e.g. `ema(last_price, 50)`). Order matters — the Rhai reads them positionally as
         *     `features[0]`, `features[1]`, … — so they are stored as an ordered array.
         */
        FeatureDef: {
            expression: string;
            name: string;
        };
        /**
         * @description Per-account fee policy. Tagged by `type` (snake_case) to mirror the engine fee model so the
         *     run-manifest bridge maps it straight into `RunConfig.accounts[].fee`. Stored as JSONB on the
         *     account; applies to every run of that account.
         *
         *     * `Rate` — ad-valorem maker/taker rates (fraction of notional), the default crypto model.
         *     * `DnseDerivatives` — DNSE VN30 futures: flat per-contract fees (venue + exchange + clearing,
         *     all VND/contract) plus a 0.05% personal income tax on order notional
         *     (`price * qty * contract_value * maintenance_margin`).
         */
        FeeConfig: {
            /** Format: double */
            maker_rate: number;
            /** Format: double */
            taker_rate: number;
            /** @enum {string} */
            type: "rate";
        } | {
            /**
             * Format: double
             * @description Phí bù trừ CKPS (VND per contract).
             */
            clearing_fee: number;
            /**
             * Format: double
             * @description Phí trả sở GDCK (VND per contract).
             */
            exchange_fee: number;
            /**
             * Format: double
             * @description Maintenance margin fraction used to size the taxable order notional (e.g. 0.1848).
             */
            maintenance_margin: number;
            /** @enum {string} */
            type: "dnse_derivatives";
            /**
             * Format: double
             * @description Phí giao dịch tại DNSE (VND per contract).
             */
            venue_fee: number;
        };
        /** @enum {string} */
        InstrumentClass: "spot" | "linear_future" | "coin_margined_future";
        /**
         * @description Simulated network latency model. Mirrors the engine's `LatencyModelType` (`tag = "name"`,
         *     snake_case) so the bridge can map it straight into `RunConfig`. **Simulation-only**: it
         *     shapes the backtest/paper gateway and is ignored in live mode (real latency applies).
         */
        LatencyModel: {
            /** @enum {string} */
            name: "zero";
        } | {
            /** Format: int64 */
            feed_ms: number;
            /** @enum {string} */
            name: "fixed";
            /** Format: int64 */
            order_ms: number;
        } | {
            /** Format: double */
            feed_ms: number;
            /** @enum {string} */
            name: "log_normal";
            /** Format: double */
            order_ms: number;
            /** Format: int64 */
            seed?: number;
            /** Format: double */
            sigma: number;
        };
        /**
         * @description Request body for `POST /api/runs` — launch a run binding a strategy to an account and a
         *     non-empty, ordered set of symbols.
         */
        LaunchRequest: {
            /** Format: uuid */
            account_id: string;
            data_kind?: components["schemas"]["MarketDataKind"];
            execution?: components["schemas"]["ExecutionSettings"] | null;
            /**
             * @description Additional accounts in leg order (arbitrage: exactly one — leg2). Each must be owned
             *     by the caller, like `account_id`. Empty for single-account strategies.
             */
            extra_account_ids?: string[];
            live_condition?: components["schemas"]["LiveConditionSettings"] | null;
            mode: components["schemas"]["RunMode"];
            params?: Record<string, never> | null;
            starting_balances?: components["schemas"]["StartingBalances"] | null;
            /** Format: uuid */
            strategy_id: string;
            symbol_ids: string[];
        };
        /**
         * @description Virtual-channel cost model + queue sizing (mirrors the engine `LiveConditionConfig`).
         *     being `Some` selects the backtest pipeline, and the queue caps size the backtest drop-sim —
         *     paper/live use the live pipeline and ignore this. Kept per-run so the bridge can feed it
         *     once backtest runs exist. Stored as `Some` for paper/backtest, `None` for live.
         */
        LiveConditionSettings: {
            /** Format: int64 */
            cost_process_l2_ns?: number;
            /** Format: int64 */
            cost_process_trade_ns?: number;
            l2_queue_capacity?: number;
            trade_queue_capacity?: number;
        };
        ManifestAccount: {
            account_type: components["schemas"]["AccountType"];
            /**
             * @description Starting balances (currency → amount). **Paper:** from the launch dialog. **Live:**
             *     exchange snapshot (TODO). Fee rates / leverages are applied by the bridge (defaults) or
             *     the live snapshot, not stored here yet.
             */
            balances?: {
                [key: string]: number;
            };
            fee?: components["schemas"]["FeeConfig"];
            /** Format: uuid */
            id: string;
            name: string;
            risk?: components["schemas"]["RiskConfig"];
            /**
             * @description Settlement (accounting) currency for equity/margin — named to avoid confusion with a
             *     symbol's base/quote asset. Maps to the engine `AccountConfig.settlement_currency`.
             *     **Paper:** supplied at launch (a paper run is a simulation). **Live:** fetched from the
             *     exchange snapshot (empty here; the bridge fills it at engine init).
             */
            settlement_currency?: string;
            /** Format: uuid */
            venue_id: string;
            venue_name: string;
            venue_type: components["schemas"]["VenueType"];
        };
        ManifestStrategy: {
            code: string;
            /**
             * @description Ordered feature definitions the strategy consumes (alpha-engine DSL). Maps directly to
             *     the engine `RunConfig.features`; order is the positional contract with the Rhai.
             */
            features?: components["schemas"]["FeatureDef"][];
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description `sha256(code)` hex — the source identity the engine's run hash keys on. Replaces what the
             *     strategy-package registry used to compute via `hash_source`.
             */
            source_hash?: string;
            strategy_type: components["schemas"]["StrategyType"];
            /**
             * Format: int32
             * @description Monotonic version of the strategy (bumped whenever its `code` changes). Carried into the
             *     engine `StrategyRunConfig.version` now that the strategy-package registry is gone.
             */
            version?: number;
        };
        ManifestSymbol: {
            /** @description Base/quote assets — the bridge registers these in the engine's currency registry. */
            base_asset?: string;
            /**
             * Format: double
             * @description Contract multiplier (point value). Defaults to 1 for older manifests without it.
             */
            contract_value?: number;
            /** Format: uuid */
            id: string;
            instrument_class: components["schemas"]["InstrumentClass"];
            /** Format: double */
            lot_size?: number | null;
            quote_asset?: string;
            symbol: string;
            /** @description Dense engine `SymbolId` (this entry's index within [`RunManifest::symbols`]). */
            symbol_id: number;
            /** Format: double */
            tick_size?: number | null;
            /** Format: uuid */
            venue_id: string;
        };
        /**
         * @description The market-data a run consumes — chosen in the launch UI. Drives the engine
         *     selection in the manifest bridge: `Tick` → the HFT (L2) engine; `Bar` → the MFT
         *     (OHLC) engine, subscribing the venue's closed-bar stream at `interval`.
         *
         *     `interval` is the exchange label (`"1m"`, `"5m"`, `"1h"`, …), parsed to a
         *     millisecond interval on the engine side. Snake_case tagged form on the wire:
         *     `{"kind":"tick"}` / `{"kind":"bar","interval":"1m"}`.
         */
        MarketDataKind: {
            /** @enum {string} */
            kind: "tick";
        } | {
            interval: string;
            /** @enum {string} */
            kind: "bar";
        };
        /** @description Request body for creating an account (`POST /api/accounts`). Both credentials required. */
        NewAccount: {
            account_type: components["schemas"]["AccountType"];
            api_key: string;
            fee?: components["schemas"]["FeeConfig"];
            name: string;
            risk?: components["schemas"]["RiskConfig"];
            secret_key: string;
            /** Format: uuid */
            venue_id: string;
        };
        /** @description Request body for creating a venue (`POST /api/venues`). */
        NewVenue: {
            name: string;
            venue_type: components["schemas"]["VenueType"];
        };
        /**
         * @description Per-account risk policy. Tagged by `type` (snake_case) to mirror the engine's `RiskConfig`
         *     enum so the run-manifest bridge maps it straight into `RunConfig.accounts[].risk`. `None`
         *     means no limits. Stored as JSONB on the account; applies to every run of that account.
         */
        RiskConfig: {
            /** @enum {string} */
            type: "none";
        } | {
            /** Format: double */
            max_order_value: number;
            /** Format: double */
            min_order_value: number;
            /** @enum {string} */
            type: "spot";
        } | {
            /** Format: double */
            max_leverage: number;
            /** Format: double */
            max_notional: number;
            /** @enum {string} */
            type: "linear_futures";
        } | {
            /** Format: double */
            max_leverage: number;
            /** Format: double */
            max_notional: number;
            /** @enum {string} */
            type: "inverse_futures";
        };
        /** @description A strategy run as returned to API clients. */
        Run: {
            /** Format: uuid */
            account_id?: string | null;
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            /** Format: uuid */
            id: string;
            manifest: components["schemas"]["RunManifest"];
            mode: components["schemas"]["RunMode"];
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            stopped_at?: string | null;
            /** Format: uuid */
            strategy_id?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Self-contained snapshot of everything a run binds together, persisted as JSONB. Shaped to
         *     mirror the engine `RunConfig` so a future `ControlPlane::run()` can reconstruct it without
         *     re-reading the live strategy/account/symbol rows (which may have since changed or been
         *     deleted).
         */
        RunManifest: {
            account: components["schemas"]["ManifestAccount"];
            data_kind?: components["schemas"]["MarketDataKind"];
            execution?: components["schemas"]["ExecutionSettings"];
            /**
             * @description Additional accounts beyond the primary, in leg order. Only arbitrage runs use this
             *     today: `account` is leg1 and `extra_accounts[0]` is leg2 (the engine reads
             *     `strategies[].accounts` positionally). Empty for every other strategy type, and for
             *     manifests persisted before this field existed.
             */
            extra_accounts?: components["schemas"]["ManifestAccount"][];
            live_condition?: components["schemas"]["LiveConditionSettings"] | null;
            mode: components["schemas"]["RunMode"];
            /** @description Strategy parameters (free-form). Empty until params are wired through the UI. */
            params?: Record<string, never>;
            strategy: components["schemas"]["ManifestStrategy"];
            /**
             * @description Ordered: each symbol's position in this list **is** its engine `SymbolId` (the dense
             *     `index_vec` index used on the hotpath). Do not reorder once persisted.
             */
            symbols: components["schemas"]["ManifestSymbol"][];
        };
        /**
         * @description The execution mode of a strategy run. Snake_case is the canonical wire/storage form,
         *     shared by the JSON API, the `strategy_runs.mode` column, and (eventually) the engine
         *     `RunConfig`. `Backtest` is intentionally omitted until the dataset feature lands.
         * @enum {string}
         */
        RunMode: "paper" | "live" | "backtest";
        /**
         * @description Lifecycle of a [`Run`]. `Pending` is reserved for future async launches; the current
         *     record-only launch path goes straight to `Running`. Snake_case is the storage/wire form.
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "stopped" | "failed" | "completed" | "paused";
        /**
         * @description Headline performance metrics for a run. `net_pnl`/`total_fee` come straight from the
         *     per-symbol attribution in `pnl.parquet`; the risk metrics (`sharpe`, `max_drawdown`,
         *     `win_rate`) are derived from the realized-PnL series reconstructed from `fills.parquet`.
         */
        RunSummary: {
            /** @description Absolute path to the run's artifact directory (`RUNS_DIR/<run_id>/`). */
            artifact_root: string;
            /**
             * Format: double
             * @description Largest peak-to-trough drop of the cumulative realized-PnL curve, in PnL units.
             */
            max_drawdown: number;
            /**
             * Format: double
             * @description Sum of per-symbol `net_pnl` (already net of fees).
             */
            net_pnl: number;
            /**
             * Format: double
             * @description Per-closing-trade Sharpe: `mean / std` of realized-trade PnLs. **Not annualized** — the
             *     fill series has no uniform sampling period, so this is a unitless dispersion-adjusted
             *     mean, not a calendar Sharpe.
             */
            sharpe: number;
            /** Format: double */
            total_fee: number;
            /**
             * Format: int32
             * @description Number of fills (execution rows in `fills.parquet`), i.e. the trade-history row count.
             */
            total_trades: number;
            /**
             * Format: double
             * @description Fraction of closing (round-trip-reducing) trades with positive realized PnL, in `[0, 1]`.
             */
            win_rate: number;
        };
        /**
         * @description Paper-run starting account state supplied at launch. A paper run is a simulation, so it does
         *     not draw real exchange balances; live runs fetch real balances instead. Feeds the manifest's
         *     `ManifestAccount.{settlement_currency,balances}`.
         */
        StartingBalances: {
            balances: {
                [key: string]: number;
            };
            settlement_currency: string;
        };
        /** @description A strategy as returned to API clients (includes the Rhai source). */
        Strategy: {
            code: string;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            features: components["schemas"]["FeatureDef"][];
            /** Format: uuid */
            id: string;
            name: string;
            strategy_type: components["schemas"]["StrategyType"];
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int32
             * @description Monotonic version, bumped server-side whenever `code` changes.
             */
            version: number;
        };
        /** @description Request body for create (`POST /api/strategies`) and update (`PUT /api/strategies/:id`). */
        StrategyInput: {
            code?: string;
            description?: string | null;
            features?: components["schemas"]["FeatureDef"][];
            name: string;
            strategy_type: components["schemas"]["StrategyType"];
        };
        /**
         * @description The execution style of a strategy. Snake_case is the canonical wire/storage form, shared
         *     by the YAML run-config, the JSON API, and the Postgres `strategies.strategy_type` column.
         * @enum {string}
         */
        StrategyType: "taker" | "maker" | "arbitrage";
        /** @description A tradable instrument in the catalog, as returned to API clients. */
        Symbol: {
            base_asset: string;
            /**
             * Format: double
             * @description Contract multiplier (point value). 1 for spot/crypto; e.g. 100000 for VN30 futures.
             */
            contract_value: number;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            instrument_class: components["schemas"]["InstrumentClass"];
            /** Format: double */
            lot_size?: number | null;
            quote_asset: string;
            status: string;
            symbol: string;
            /** Format: double */
            tick_size?: number | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            venue_id: string;
        };
        /**
         * @description Per-symbol PnL attribution, one row per symbol in `pnl.parquet`. `symbol` is resolved from
         *     the run manifest (the parquet only stores the dense engine `symbol_id`).
         */
        SymbolPnlSummary: {
            /**
             * Format: double
             * @description `adv_sel_open + adv_sel_close` — adverse-selection cost.
             */
            adverse_selection: number;
            /** Format: double */
            net_pnl: number;
            /**
             * Format: double
             * @description `signal_pnl` — PnL attributable to mid-price movement after entry.
             */
            signal_pnl: number;
            /**
             * Format: double
             * @description `spread_pnl_open + spread_pnl_close` — edge captured/paid crossing the spread.
             */
            spread_capture: number;
            symbol: string;
            /** Format: int64 */
            symbol_id: number;
            /** Format: double */
            total_fee: number;
        };
        /** @description A page of trade history plus the total row count for the UI's pager. */
        TradePage: {
            /** Format: int64 */
            page: number;
            rows: components["schemas"]["TradeRow"][];
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description One execution from `fills.parquet`, surfaced in the paginated trade-history table. */
        TradeRow: {
            /** Format: double */
            adv_sel_2s: number;
            /** Format: double */
            adv_sel_30s: number;
            /** Format: double */
            adv_sel_500ms: number;
            /** Format: double */
            adv_sel_5s: number;
            /** Format: double */
            fill_price: number;
            /** Format: double */
            fill_qty: number;
            /** Format: int64 */
            fill_ts: number;
            /** Format: double */
            mid_at_fill: number;
            /** Format: int64 */
            order_id: number;
            outcome: string;
            side: string;
            /** Format: int64 */
            submitted_ts: number;
            symbol: string;
            /** Format: int64 */
            symbol_id: number;
        };
        /**
         * @description Request body for updating an account (`PUT /api/accounts/:id`).
         *
         *     `api_key` / `secret_key` are optional: omit them to keep the stored credentials (so the
         *     account can be renamed or re-typed without re-entering secrets); provide them to rotate.
         *     `risk` is not a secret, so it is always replaced with the supplied value (default `None`).
         */
        UpdateAccount: {
            account_type: components["schemas"]["AccountType"];
            api_key?: string | null;
            fee?: components["schemas"]["FeeConfig"];
            name: string;
            risk?: components["schemas"]["RiskConfig"];
            secret_key?: string | null;
            /** Format: uuid */
            venue_id: string;
        };
        /** @description Request body for updating a venue (`PUT /api/venues/:id`). */
        UpdateVenue: {
            name: string;
            venue_type: components["schemas"]["VenueType"];
        };
        /**
         * @description A user authenticated via the external auth service. Returned by `GET /api/auth/me`
         *     and deserialized from the auth service's `/me` response.
         */
        User: {
            email: string;
            user_id: string;
            username?: string | null;
        };
        /** @description Request body for `POST /api/strategies/validate-features`. */
        ValidateFeaturesRequest: {
            features: components["schemas"]["FeatureDef"][];
        };
        /** @description Request body for `POST /api/strategies/validate`. */
        ValidateRequest: {
            code: string;
            /**
             * @description The strategy's features — only their count is used, to size the `features`
             *     array so valid index accesses don't halt the test-eval early.
             */
            features?: components["schemas"]["FeatureDef"][];
            strategy_type?: components["schemas"]["StrategyType"] | null;
        };
        /**
         * @description A venue as returned to API clients. `venue_type` is the strongly-typed enum; it is
         *     persisted as snake_case TEXT in the `venues.venue_type` column.
         */
        Venue: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            updated_at: string;
            venue_type: components["schemas"]["VenueType"];
        };
        /**
         * @description The kind of trading venue / exchange a [`Venue`] connects to.
         *
         *     The snake_case form (`binance_spot`, `binance_futures`, `tcbs`, `dnse`) is the
         *     canonical wire/storage representation, shared by the YAML run-config, the JSON API,
         *     and the Postgres `venues.venue_type` text column.
         * @enum {string}
         */
        VenueType: "binance_spot" | "binance_futures" | "tcbs" | "dnse";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
